### ISSUE TITLE
Erkennen ob sich innerhalb einer Bounding Box ein physischer Würfel befindet

### ISSUE THREAD

**Issue by eduDorus** [eduDorus/PAWI#18]
Es soll erkannt werden, ob sich innerhalb einer Bounding Box ein physisches Objekt befindet oder nicht. Dies könnte den Aufbau einer Bahn mittels einer Anleitung vereinfachen bzw. das Bestätigen dass sich ein Element an der richtigen Stelle befindet Automatisieren.

**Comment by culas** [comment]
Änderung nach Meeting: Konzept mit Hittesting für diesen Prototyp ausformulieren und in Dokumentation festhalten. Im Ausblick als mögliches Projekt aufführen.

**Comment by culas** [comment]
Wurde erledigt
